### ISSUE TITLE
App: Datafrete

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-datafrete#1]
> Tudo pronto, só falta publicar (aguardando possível homologação) :smile: 

@vitorrgg arruma um ícone pra este app também por favor?

**Comment by leomp12** [comment]
https://www.datafrete.com/

**Comment by vitorrgg** [comment]
![datafrete](https://user-images.githubusercontent.com/35348281/90303110-b5c5ad80-de81-11ea-84b4-4f62cdf6c9cf.png)
